name: cypress

on:
  workflow_dispatch:
    push:
      branches: [main]
  pull_request:
    branches: [main]

env:
  CYPRESS_CACHE_FOLDER: '${GITHUB_WORKSPACE}/.cypress-cache'

jobs:
  prepare_e2e:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:10.10.0
      options: --user 1001
    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install && pnpm cypress install

      - name: Build App
        run: pnpm generate

      - name: Build App Results
        uses: actions/upload-artifact@v3
        with:
          path: dist

  e2e:
    runs-on: ubuntu-latest
    needs: prepare_e2e
    container:
      image: cypress/included:10.10.0
      options: --user 1001
    strategy:
      matrix:
        index: [1, 2, 3, 4, 5] # [1, ..., n] where n === parallelSize in e2e-run-tests.js
    steps:
      - uses: actions/checkout@v3

      - name: Use Generated App
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install && pnpm cypress install

      - name: Cypress run
        timeout-minutes: 10
        uses: Wandalen/wretry.action@master
        with:
          command: pnpm start:static & pnpm wait-on http://localhost:9090 && MATRIX=${{ matrix.index }} node tests/cypress/e2e-run-tests.js
          attempt_limit: 3

      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          path: ./cypress/screenshots/
