name: cypress

on:
  workflow_dispatch:
    push:
      branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-prepare:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:10.10.0
      options: --user 1001
    env:
      CYPRESS_CACHE_FOLDER: '${GITHUB_WORKSPACE}/.cypress-cache'
    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            .nuxt
            .output
            dist
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install && pnpm cypress install

      - name: Build App
        run: pnpm generate

      - name: Cache build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            ./.nuxt
            ./.output
            ./dist
            ./node_modules
          key: ${{ github.sha }}

  e2e:
    runs-on: ubuntu-latest
    needs: e2e-prepare
    container:
      image: cypress/included:10.10.0
      options: --user 1001
    env:
      CYPRESS_CACHE_FOLDER: '${GITHUB_WORKSPACE}/.cypress-cache'
    strategy:
      matrix:
        index: [1, 2, 3, 4, 5] # [1, ..., n] where n === parallelSize in e2e-run-tests.js
    steps:
      - uses: actions/checkout@v3

      - name: Restore cache build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            ./.nuxt
            ./.output
            ./dist
            ./node_modules
          key: ${{ github.sha }}

      - name: check directory
        run: ls -la

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm install && pnpm cypress install

      - name: Cypress run
        run: pnpm start:static & pnpm wait-on http://localhost:9090 && MATRIX=${{ matrix.index }} node tests/cypress/e2e-run-tests.js

      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          path: ./cypress/screenshots/
