name: Linter

on:
  pull_request:
    branches: [main]

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/pnpm-install

      - uses: CatChen/eslint-suggestion-action@v2
